routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/', 'HomeController@index')->name('home');
Route::group(['prefix'=>'wp-admin','middleware' => ['auth']], function() {
    Route::get('/', function () {
        return view('admin.index');
    })->name('admin');
    Route::resource('roles','Admin\RoleController');
    Route::get('site','Admin\SiteController@update')->name('site.create');
    Route::post('site','Admin\SiteController@store')->name('site.store');
    Route::resource('user','Admin\UserController');
    //newcate
    Route::resource('postcate', 'Admin\CategoryPostController');
    Route::resource('post', 'Admin\PostController');
    Route::resource('link', 'Admin\PostLinkController');
    //Page
    Route::resource('page', 'Admin\PageController');
    //slide
    Route::resource('slide', 'Admin\SlideController');
    //slide
    Route::resource('contact', 'Admin\ContactController');
    Route::resource('reg', 'Admin\RegController');
    //slide
    Route::resource('tag', 'Admin\TagController');
    //slide
    Route::resource('comment', 'Admin\CommentController');
    Route::post('comment/{id}', 'Admin\CommentController@storeedit')->name('commentedit');
    Route::get('commentdel/{id}', 'Admin\CommentController@delcommentfront')->name('delcommentfront');

        Route::get('/menu', array('as' => 'menu', 'uses' => 'Admin\MenuController@index'));
        Route::post('/addcustommenu', array('as' => 'haddcustommenu', 'uses' => 'Admin\MenuController@addcustommenu'));
        Route::post('/deleteitemmenu', array('as' => 'hdeleteitemmenu', 'uses' => 'Admin\MenuController@deleteitemmenu'));
        Route::post('/deletemenug', array('as' => 'hdeletemenug', 'uses' => 'Admin\MenuControllerMenuController@deletemenug'));
        Route::post('/createnewmenu', array('as' => 'hcreatenewmenu', 'uses' => 'Admin\MenuController@createnewmenu'));
        Route::post('/generatemenucontrol', array('as' => 'hgeneratemenucontrol', 'uses' => 'Admin\MenuController@generatemenucontrol'));
        Route::post('/updateitem', array('as' => 'hupdateitem', 'uses' => 'Admin\MenuController@updateitem'));


});
Route::get('/lien-he', function () {
    return view('fe.lienhe');
})->name('lienhe');
Route::get('/dang-ky-xet-tuyen', function () {
    return view('fe.dangky');
})->name('dangky');
Route::get('page-not-found',function(){
   return view('fe.404'); 
})->name('404');
Route::get('tag/{slug}', 'HomeController@tag')->name('tag');
Route::post('/contact', 'HomeController@contact')->name('contact');
Route::post('/contactm', 'HomeController@contactm')->name('contactm');
Route::post('/reg', 'HomeController@xettuyen')->name('reg');
Route::post('/comment/store', 'CommentController@store')->name('comment.add');
Route::post('/reply/store', 'CommentController@replyStore')->name('reply.add');
Route::get('/{slug}', 'HomeController@allslug')->name('allslug');

app/Models/Comment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = [
        'name', 'email', 'phone','body','parent_id','id','post_id','is_approved','user_id'
    ];

    public function user()
    {
        return $this->belongsTo('App\User');
    }
    public function post()
    {
        return $this->belongsTo('App\Models\Post');
    }

    public function replies()
    {
        return $this->hasMany('App\Models\Comment','parent_id')->where('is_approved',1);
    }
}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Repositories\Comment\CommentRepositoryInterface;
use DataTables;
use Carbon\Carbon;

class CommentController extends Controller
{
    protected $repoComment;
    public function __construct(CommentRepositoryInterface $repoComment)
    {
        $this->repoComment = $repoComment;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //Comment::where('name','admin')->update(['user_id'=>6]);
        if ($request->ajax()) {

            $data = $this->repoComment->latest()->where('user_id',0)->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('active', function($row){

                    $rolename = "";
                    if($row->is_approved == 0){
                        $rolename = "Ẩn";
                    }else
                    {
                        $rolename = "Hiện";
                    }

                    return $rolename;
                })
                ->rawColumns(['active'])
                ->addColumn('action', function($row){

                    $btn = '<a  href="'.route('comment.edit', $row->id).'" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="AN HIEN">
                        <i class="la la-refresh"></i></a><a  href="'.route('comment.show', $row->id).'" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="SUA">
                        <i class="la la-edit"></i></a><a  href="'.route('allslug', $row->post->slugs->slug).'" target="_blank" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="BAI VIET">
                        <i class="la la-eye"></i></a><a  href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill deleteUser" title="XOA">
                        <i class="la la-close"></i></a>';

                    return $btn;
                })

                ->rawColumns(['action'])
                ->editColumn('created_at', function ($row) {
                    $carbon = new Carbon($row->created_at);
                    return $carbon->toDayDateTimeString('vi');
                })

                ->make(true);
        }
        return view('admin.comment.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function storeedit(Request $request,$id)
    {
        $this->repoComment->update($id,[
            'body'=> $request->body,
            'name'=> $request->name
        ]);
        return redirect()->route('comment.index')
        ->with('success','Sửa Comment thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = $this->repoComment->find($id);
        return view('admin.comment.edit',compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = $this->repoComment->find($id);
        $data->is_approved = !$data->is_approved;
        $data->save();
        return redirect()->route('comment.index')
        ->with('success','Active Comment thành công');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->repoComment->update($id,[
            'body'=> $request->body,
            'name'=> $request->name
        ]);
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->repoComment->delete($id);
        return redirect()->route('comment.index')
                        ->with('success','Xoá Comment thành công');
    }


    public function delcommentfront($id)
    {
        $this->repoComment->delete($id);
        return redirect()->back()
                        ->with('successedit','Xoá Comment thành công');
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Comment;
use App\Models\Post;
use App\Http\Requests\CommentUserRequest;
use Illuminate\Support\Facades\Auth;
use Mail;

class CommentController extends Controller
{


    public function store(CommentUserRequest $request)
    {
        $data = new Comment();
        $data->post_id = $request->post_id;
        $data->name = $request->name;
        $data->parent_id = 0;
        if (Auth::check()) {
            $data->user_id = Auth::id();
            $data->is_approved =1;
        }else{
            $data->user_id =0;
            $data->is_approved =0;  
        }
        $data->email = $request->email;
        $data->body = $request->body;
        $data->phone = $request->phone;
        $data->save();
        $post = Post::findOrFail($request->post_id);
        $data['title'] = $request->name;
        $data['phone'] = $request->phone;
        $data['admission'] = $request->body;
        $data['links'] = route('allslug', $post->slugs->slug);
        $mail = Mail::send('emails.comment', ['data'=>$data], function($message) {

            $message->to('tien2vv@gmail.com', 'Receiver Name')->cc(['diepviencongnghe@gmail.com','truongcaodangnauan@gmail.com'])

                    ->subject('DIỄN ĐÀN TUYỂN SINH 24H');
        });

        return redirect()->back();
    }

    public function replyStore(CommentUserRequest $request)
    {
        $reply = new Comment();
        $reply->post_id = $request->post_id;
        $reply->name = $request->name;
        $reply->email = $request->email;
        if (Auth::check()) {
            $reply->user_id = Auth::id();
            $reply->is_approved =1;
        }else{
            $data->user_id =0;
            $data->is_approved =0;  
        }
        $reply->body = $request->body;
        $reply->phone = $request->phone;
        $reply->parent_id = $request->comment_id;

        $reply->save();
        $post = Post::findOrFail($request->post_id);
        $data['title'] = $request->name;
        $data['phone'] = $request->phone;
        $data['admission'] = $request->body;
        $data['links'] = route('allslug', $post->slugs->slug);
        $mail = Mail::send('emails.comment',  ['data'=>$data], function($message) {

            $message->to('tien2vv@gmail.com', 'Receiver Name')->cc(['diepviencongnghe@gmail.com','truongcaodangnauan@gmail.com'])

                    ->subject('DIỄN ĐÀN TUYỂN SINH 24H');
        });

        return  redirect()->back();

    }
}

resources/views/admin/comment/create.blade.php
<?php ?>

@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        Tạo tag bài viết
                    </h3>
                </div>
            </div>
            <div class="m-portlet__head-tools">
                <ul class="m-portlet__nav">
                    <li class="m-portlet__nav-item">
                    </li>
                </ul>
            </div>

        </div>
        <div class="m-portlet__body">

            @include('admin.errors')
            <form class="form-horizontal" style="width:100%" role="form" method="POST"
                action="{{ route('tag.store') }}">

                <div class="row">

                    {{ csrf_field() }}
                    <div class="col-md-9">


                        <div
                            class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-12 control-label">Tên tag bài viết</label>

                            <div class="col-md-12">
                                <input id="name" type="text" class="form-control" name="name"
                                    value="{{ old('name') }}" onkeyup="ChangeToSlug()" required
                                    autofocus>

                                @if($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>




                        <div
                            class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                            <label for="slug" class="col-md-12 control-label">Slug Tag bài viết</label>

                            <div class="col-md-12">
                                <input id="slug" type="text" class="form-control" name="slug"
                                    value="{{ old('slug') }}">

                                @if($errors->has('slug'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('slug') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <button type="submit" class="btn btn-primary">
                                    Tạo mới
                                </button>

                                <a class="btn btn-link" href="{{ route('tag.index') }}">
                                    Hủy
                                </a>
                            </div>
                        </div>
                    </div>

                </div>
            </form>
        </div>
    </div>
</div>

<script src="{{ asset('/vendor/laravel-filemanager/js/stand-alone-button.js') }}"></script>
{{-- <script src="{{ asset('js/tinymce.min.js') }}"></script> --}}
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script type="text/javascript">
    $('#lfm').filemanager('image');

    function ChangeToSlug() {
        var title, slug;

        //Lấy text từ thẻ input title
        title = document.getElementById("name").value;

        //Đổi chữ hoa thành chữ thường
        slug = title.toLowerCase();

        //Đổi ký tự có dấu thành không dấu
        slug = slug.replace(/á|à|ả|ạ|ã|ă|ắ|ằ|ẳ|ẵ|ặ|â|ấ|ầ|ẩ|ẫ|ậ/gi, 'a');
        slug = slug.replace(/é|è|ẻ|ẽ|ẹ|ê|ế|ề|ể|ễ|ệ/gi, 'e');
        slug = slug.replace(/i|í|ì|ỉ|ĩ|ị/gi, 'i');
        slug = slug.replace(/ó|ò|ỏ|õ|ọ|ô|ố|ồ|ổ|ỗ|ộ|ơ|ớ|ờ|ở|ỡ|ợ/gi, 'o');
        slug = slug.replace(/ú|ù|ủ|ũ|ụ|ư|ứ|ừ|ử|ữ|ự/gi, 'u');
        slug = slug.replace(/ý|ỳ|ỷ|ỹ|ỵ/gi, 'y');
        slug = slug.replace(/đ/gi, 'd');
        //Xóa các ký tự đặt biệt
        slug = slug.replace(/\`|\~|\!|\@|\#|\||\$|\%|\^|\&|\*|\(|\)|\+|\=|\,|\.|\/|\?|\>|\<|\'|\"|\:|\;|_/gi, '');
        //Đổi khoảng trắng thành ký tự gạch ngang
        slug = slug.replace(/ /gi, "-");
        //Đổi nhiều ký tự gạch ngang liên tiếp thành 1 ký tự gạch ngang
        //Phòng trường hợp người nhập vào quá nhiều ký tự trắng
        slug = slug.replace(/\-\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-\-/gi, '-');
        slug = slug.replace(/\-\-\-/gi, '-');
        slug = slug.replace(/\-\-/gi, '-');
        //Xóa các ký tự gạch ngang ở đầu và cuối
        slug = '@' + slug + '@';
        slug = slug.replace(/\@\-|\-\@|\@/gi, '');
        //In slug ra textbox có id “slug”
        // var url = '{{ url('/page/') }}';
        // document.getElementById('link').value = url +'/'+ slug;
        document.getElementById('slug').value = slug;

    }
    var editor_config = {
        path_absolute: "/",
        selector: "textarea.my-editor",
        plugins: [
            "advlist autolink lists link image charmap print preview hr anchor pagebreak",
            "searchreplace wordcount visualblocks visualchars code fullscreen",
            "insertdatetime media nonbreaking save table contextmenu directionality",
            "emoticons template paste textcolor colorpicker textpattern"
        ],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image media | code",
        relative_urls: false,
        image_caption: true,
        image_title: true,
        style_formats: [{
            title: "Image",
            items: [{
                    title: "Left",
                    icon: "alignleft",
                    selector: "img,figure",
                    classes: "image align-left"
                },
                {
                    title: "Center",
                    icon: "aligncenter",
                    selector: "img,figure",
                    classes: "image align-center"
                },
                {
                    title: "Right",
                    icon: "alignright",
                    selector: "img,figure",
                    classes: "image align-right"
                },
                {
                    title: "Full",
                    icon: "alignjustify",
                    selector: "img,figure",
                    classes: "image featured"
                }
            ]
        }],
        style_formats_merge: false,
        menubar: true,
        file_browser_callback: function (field_name, url, type, win) {
            var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName(
                'body')[0].clientWidth;
            var y = window.innerHeight || document.documentElement.clientHeight || document
                .getElementsByTagName('body')[0].clientHeight;

            var cmsURL = editor_config.path_absolute + 'laravel-filemanager?field_name=' + field_name;
            if (type == 'image') {
                cmsURL = cmsURL + "&type=Images";
            } else {
                cmsURL = cmsURL + "&type=Files";
            }

            tinyMCE.activeEditor.windowManager.open({
                file: cmsURL,
                title: 'Filemanager',
                width: x * 0.8,
                height: y * 0.8,
                resizable: "yes",

                close_previous: "no"
            });
        }
    };

    tinymce.init(editor_config);
</script>
<script>
    $("#selectbtn-tag").click(function () {
        $("#selectall-tag > option").prop("selected", "selected");
        $("#selectall-tag").trigger("change");
    });
    $("#deselectbtn-tag").click(function () {
        $("#selectall-tag > option").prop("selected", "");
        $("#selectall-tag").trigger("change");
    });

    $(document).ready(function () {
        $('.select2').select2();
    });
</script>
</div>


@endsection

resources/views/admin/comment/index.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
      <div class="col-md-12">
            @if($message = Session::get('success'))
                  <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <strong>{{ $message }}</strong>
                  </div>
            @endif
      </div>
      <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                  <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                              <h3 class="m-portlet__head-text">
                                    Comment Bài Viết
                              </h3>
                        </div>
                  </div>
                  <div class="m-portlet__head-tools">
                        <ul class="m-portlet__nav">
                              <li class="m-portlet__nav-item">
                              </li>
                        </ul>
                  </div>

            </div>
            <div class="m-portlet__body">

                  <!--begin: Search Form -->
                  <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                        <div class="row align-items-center">
                              <div class="col-xl-8 order-2 order-xl-1">

                              </div>
                              <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                                    {{-- <a href="{{ route('tag.create') }}"
                                    class="btn btn-info m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                    <span>
                                          <i class="la la-cart-plus"></i>
                                          <span>Tạo Mới Tag Bài Viết</span>
                                    </span>
                                    </a> --}}
                                    <div class="m-separator m-separator--dashed d-xl-none"></div>
                              </div>
                        </div>
                  </div>
                  <!--end: Search Form -->

                  <!--begin: Datatable -->
                  <div class="m_datatable" id="child_data_ajax">

                        <table class="data-table m-datatable__table">
                              <thead>
                                    <tr>
                                          <th>No</th>
                                          <th>Tên</th>
                                          <th>Email</th>
                                          <th>Phone</th>
                                          <th>Body</th>
                                          <th>Ngay</th>
                                          <th>Active</th>
                                          <th width="140px">Action</th>
                                    </tr>
                              </thead>
                              <tbody>
                              </tbody>
                        </table>
                  </div>
                  <!--end: Datatable -->
            </div>
      </div>

      @routes

            <script type="text/javascript">
                  $(document).ready(function () {
                        $.ajaxSetup({
                              headers: {
                                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                              }
                        });
                        var table = $('.data-table').DataTable({
                              processing: true,
                              serverSide: true,
                              pageLength: 20,
                              ajax: "{{ route('comment.index') }}",
                              columns: [{
                                          data: 'DT_RowIndex',
                                          name: 'DT_RowIndex'
                                    },
                                    {
                                          data: 'name',
                                          name: 'name'
                                    },
                                    {
                                          data: 'email',
                                          name: 'email'
                                    },
                                    {
                                          data: 'phone',
                                          name: 'phone'
                                    },
                                    {
                                          data: 'body',
                                          name: 'body'
                                    },
                                    {
                                          data: 'created_at',
                                          name: 'created_at'
                                    },
                                    {
                                          data: 'active',
                                          name: 'active'
                                    },
                                    {
                                          data: 'action',
                                          name: 'action',
                                          orderable: false,
                                          searchable: false
                                    },
                              ]
                        });

                        $('body').on('click', '.deleteUser', function () {
                              //$(".deleteUser").click(function(){

                              var page_id = $(this).data("id");
                              var r = confirm("Bạn chắc chắn muốn xóa !");
                              if (r == true) {
                                    $.ajax({
                                          type: "POST",
                                          data: {
                                                _method: 'delete'
                                          },
                                          url: route('comment.destroy', {
                                                id: page_id
                                          }),
                                          success: function (data) {
                                                table.draw();
                                          },
                                          error: function (data) {
                                                console.log('Error:', data);
                                          }
                                    });
                              } else {
                                    return false;
                              }

                        });
                        $(".alert").fadeTo(2000, 500).slideUp(500, function () {
                              $(".alert").slideUp(500);
                        });

                  });
            </script>
</div>
@endsection

resources/views/admin/comment/show.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Chi tiết danh mục</div>

                    <div class="panel-body">


                        <div class="form-group">
                            <label for="title" class="col-md-4 control-label">Tên danh mục</label>
                            {{ $data->title }}
                        </div>


                        <div class="form-group">
                            <label for="description" class="col-md-4 control-label">Mô tả danh mục</label>
                            {{ $data->description }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection