routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/', 'HomeController@index')->name('home');
Route::group(['prefix'=>'wp-admin','middleware' => ['auth']], function() {
    Route::get('/', function () {
        return view('admin.index');
    })->name('admin');
    Route::resource('roles','Admin\RoleController');
    Route::get('site','Admin\SiteController@update')->name('site.create');
    Route::post('site','Admin\SiteController@store')->name('site.store');
    Route::resource('user','Admin\UserController');
    //newcate
    Route::resource('postcate', 'Admin\CategoryPostController');
    Route::resource('post', 'Admin\PostController');
    Route::resource('link', 'Admin\PostLinkController');
    //Page
    Route::resource('page', 'Admin\PageController');
    //slide
    Route::resource('slide', 'Admin\SlideController');
    //slide
    Route::resource('contact', 'Admin\ContactController');
    Route::resource('reg', 'Admin\RegController');
    //slide
    Route::resource('tag', 'Admin\TagController');
    //slide
    Route::resource('comment', 'Admin\CommentController');
    Route::post('comment/{id}', 'Admin\CommentController@storeedit')->name('commentedit');
    Route::get('commentdel/{id}', 'Admin\CommentController@delcommentfront')->name('delcommentfront');

        Route::get('/menu', array('as' => 'menu', 'uses' => 'Admin\MenuController@index'));
        Route::post('/addcustommenu', array('as' => 'haddcustommenu', 'uses' => 'Admin\MenuController@addcustommenu'));
        Route::post('/deleteitemmenu', array('as' => 'hdeleteitemmenu', 'uses' => 'Admin\MenuController@deleteitemmenu'));
        Route::post('/deletemenug', array('as' => 'hdeletemenug', 'uses' => 'Admin\MenuControllerMenuController@deletemenug'));
        Route::post('/createnewmenu', array('as' => 'hcreatenewmenu', 'uses' => 'Admin\MenuController@createnewmenu'));
        Route::post('/generatemenucontrol', array('as' => 'hgeneratemenucontrol', 'uses' => 'Admin\MenuController@generatemenucontrol'));
        Route::post('/updateitem', array('as' => 'hupdateitem', 'uses' => 'Admin\MenuController@updateitem'));


});
Route::get('/lien-he', function () {
    return view('fe.lienhe');
})->name('lienhe');
Route::get('/dang-ky-xet-tuyen', function () {
    return view('fe.dangky');
})->name('dangky');
Route::get('page-not-found',function(){
   return view('fe.404'); 
})->name('404');
Route::get('tag/{slug}', 'HomeController@tag')->name('tag');
Route::post('/contact', 'HomeController@contact')->name('contact');
Route::post('/contactm', 'HomeController@contactm')->name('contactm');
Route::post('/reg', 'HomeController@xettuyen')->name('reg');
Route::post('/comment/store', 'CommentController@store')->name('comment.add');
Route::post('/reply/store', 'CommentController@replyStore')->name('reply.add');
Route::get('/{slug}', 'HomeController@allslug')->name('allslug');

resources/views/admin/link/create.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        Tạo mới link trong bài viết
                    </h3>
                </div>
            </div>
            <div class="m-portlet__head-tools">
                <ul class="m-portlet__nav">
                    <li class="m-portlet__nav-item">
                    </li>
                </ul>
            </div>

        </div>
        <div class="m-portlet__body">

            <!-- Display Validation Errors -->
            @include('admin.errors')

            <form class="form-horizontal" role="form" method="POST"
                action="{{ route('link.store') }}">
                {{ csrf_field() }}

                <div
                    class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                    <label for="name" class="col-md-4 control-label">Tiêu đề link</label>

                    <div class="col-md-12">
                        <input id="title" type="text" class="form-control" name="title"
                            value="{{ old('title') }}" required autofocus>
                    </div>
                </div>
                <div
                    class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                    <label for="link" class="col-md-4 control-label">Link</label>

                    <div class="col-md-12">
                        <input id="link" type="text" class="form-control" name="link"
                            value="{{ old('link') }}">
                    </div>
                </div>
                <div
                        class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                    <label for="alt" class="col-md-4 control-label">Alt</label>

                    <div class="col-md-12">
                        <input id="alt" type="text" class="form-control" name="alt"
                               value="{{ old('alt') }}">
                    </div>
                </div>




                <div class="form-group">
                    <div class="col-md-8 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">
                            Tạo mới
                        </button>

                        <a class="btn btn-link" href="{{ route('link.index') }}">
                            Hủy
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/admin/link/edit.blade.php
<?php ?>

@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        Sửa Link trong bài viết
                    </h3>
                </div>
            </div>
            <div class="m-portlet__head-tools">
                <ul class="m-portlet__nav">
                    <li class="m-portlet__nav-item">
                    </li>
                </ul>
            </div>

        </div>
        <div class="m-portlet__body">

            <!-- Display Validation Errors -->
            @include('admin.errors')

            <form class="form-horizontal" method="POST"
                action="{{ route('link.update', $data->id) }}">
                {{ csrf_field() }}
                {{ method_field('PATCH') }}

                <div
                        class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
                    <label for="name" class="col-md-4 control-label">Tiêu đề link</label>

                    <div class="col-md-12">
                        <input id="title" type="text" class="form-control" name="title"
                               value="{{ old('title') ? old('title') : $data->title }}" required autofocus>
                    </div>
                </div>
                <div
                        class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                    <label for="link" class="col-md-4 control-label">Link</label>

                    <div class="col-md-12">
                        <input id="link" type="text" class="form-control" name="link"
                               value="{{ old('link') ? old('link') : $data->link }}">
                    </div>
                </div>
                <div
                        class="form-group{{ $errors->has('slug') ? ' has-error' : '' }}">
                    <label for="alt" class="col-md-4 control-label">Alt</label>

                    <div class="col-md-12">
                        <input id="alt" type="text" class="form-control" name="alt"
                               value="{{ old('alt') ?old('alt') : $data->alt }}">
                    </div>
                </div>



                <div class="form-group">
                    <div class="col-md-8 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">
                            Sửa
                        </button>

                        <a class="btn btn-link" href="{{ route('link.index') }}">
                            Hủy
                        </a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/admin/link/index.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
      <div class="col-md-12">
            @if($message = Session::get('success'))
                  <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <strong>{{ $message }}</strong>
                  </div>
            @endif
      </div>
      <div class="m-portlet m-portlet--mobile">
            <div class="m-portlet__head">
                  <div class="m-portlet__head-caption">
                        <div class="m-portlet__head-title">
                              <h3 class="m-portlet__head-text">
                                    Link trong bài viết
                              </h3>
                        </div>
                  </div>
                  <div class="m-portlet__head-tools">
                        <ul class="m-portlet__nav">
                              <li class="m-portlet__nav-item">
                              </li>
                        </ul>
                  </div>

            </div>
            <div class="m-portlet__body">

                  <!--begin: Search Form -->
                  <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                        <div class="row align-items-center">
                              <div class="col-xl-8 order-2 order-xl-1">

                              </div>
                              <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                                    <a href="{{ route('link.create') }}"
                                          class="btn btn-info m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                                          <span>
                                                <i class="la la-cart-plus"></i>
                                                <span>Thêm link bài viết</span>
                                          </span>
                                    </a>
                                    <div class="m-separator m-separator--dashed d-xl-none"></div>
                              </div>
                        </div>
                  </div>
                  <!--end: Search Form -->

                  <!--begin: Datatable -->
                  <div class="m_datatable" id="child_data_ajax">

                        <table class="data-table m-datatable__table">
                              <thead>
                                    <tr>
                                          <th>No</th>
                                          <th>Link Title</th>
                                          <th width="120px">Action</th>
                                    </tr>
                              </thead>
                              <tbody>
                              </tbody>
                        </table>
                  </div>
                  <!--end: Datatable -->
            </div>
      </div>

      @routes

            <script type="text/javascript">
                  $(document).ready(function () {
                        $.ajaxSetup({
                              headers: {
                                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                              }
                        });
                        var table = $('.data-table').DataTable({
                              processing: true,
                              serverSide: true,
                              pageLength:50,
                              ajax: "{{ route('link.index') }}",
                              columns: [{
                                          data: 'DT_RowIndex',
                                          name: 'DT_RowIndex'
                                    },
                                    {
                                          data: 'title',
                                          name: 'title'
                                    },
                                    {
                                          data: 'action',
                                          name: 'action',
                                          orderable: false,
                                          searchable: false
                                    },
                              ]
                        });

                        $('body').on('click', '.deleteUser', function () {
                              //$(".deleteUser").click(function(){

                              var page_id = $(this).data("id");
                              var r = confirm("Bạn chắc chắn muốn xóa !");
                              if (r == true) {
                                    $.ajax({
                                          type: "POST",
                                          data: {
                                                _method: 'delete'
                                          },
                                          url: route('link.destroy', {
                                                id: page_id
                                          }),
                                          success: function (data) {
                                                table.draw();
                                          },
                                          error: function (data) {
                                                console.log('Error:', data);
                                          }
                                    });
                              } else {
                                    return false;
                              }

                        });
                        $(".alert").fadeTo(2000, 500).slideUp(500, function () {
                              $(".alert").slideUp(500);
                        });

                  });
            </script>
</div>
@endsection

resources/views/admin/link/show.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Chi tiết danh mục</div>

                    <div class="panel-body">


                        <div class="form-group">
                            <label for="title" class="col-md-4 control-label">Tên danh mục</label>
                            {{ $data->title }}
                        </div>


                        <div class="form-group">
                            <label for="description" class="col-md-4 control-label">Mô tả danh mục</label>
                            {{ $data->description }}
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection