routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
    \UniSharp\LaravelFilemanager\Lfm::routes();
});

Route::get('/', 'HomeController@index')->name('home');
Route::group(['prefix'=>'wp-admin','middleware' => ['auth']], function() {
    Route::get('/', function () {
        return view('admin.index');
    })->name('admin');
    Route::resource('roles','Admin\RoleController');
    Route::get('site','Admin\SiteController@update')->name('site.create');
    Route::post('site','Admin\SiteController@store')->name('site.store');
    Route::resource('user','Admin\UserController');
    //newcate
    Route::resource('postcate', 'Admin\CategoryPostController');
    Route::resource('post', 'Admin\PostController');
    Route::resource('link', 'Admin\PostLinkController');
    //Page
    Route::resource('page', 'Admin\PageController');
    //slide
    Route::resource('slide', 'Admin\SlideController');
    //slide
    Route::resource('contact', 'Admin\ContactController');
    Route::resource('reg', 'Admin\RegController');
    //slide
    Route::resource('tag', 'Admin\TagController');
    //slide
    Route::resource('comment', 'Admin\CommentController');
    Route::post('comment/{id}', 'Admin\CommentController@storeedit')->name('commentedit');
    Route::get('commentdel/{id}', 'Admin\CommentController@delcommentfront')->name('delcommentfront');

        Route::get('/menu', array('as' => 'menu', 'uses' => 'Admin\MenuController@index'));
        Route::post('/addcustommenu', array('as' => 'haddcustommenu', 'uses' => 'Admin\MenuController@addcustommenu'));
        Route::post('/deleteitemmenu', array('as' => 'hdeleteitemmenu', 'uses' => 'Admin\MenuController@deleteitemmenu'));
        Route::post('/deletemenug', array('as' => 'hdeletemenug', 'uses' => 'Admin\MenuControllerMenuController@deletemenug'));
        Route::post('/createnewmenu', array('as' => 'hcreatenewmenu', 'uses' => 'Admin\MenuController@createnewmenu'));
        Route::post('/generatemenucontrol', array('as' => 'hgeneratemenucontrol', 'uses' => 'Admin\MenuController@generatemenucontrol'));
        Route::post('/updateitem', array('as' => 'hupdateitem', 'uses' => 'Admin\MenuController@updateitem'));


});
Route::get('/lien-he', function () {
    return view('fe.lienhe');
})->name('lienhe');
Route::get('/dang-ky-xet-tuyen', function () {
    return view('fe.dangky');
})->name('dangky');
Route::get('page-not-found',function(){
   return view('fe.404'); 
})->name('404');
Route::get('tag/{slug}', 'HomeController@tag')->name('tag');
Route::post('/contact', 'HomeController@contact')->name('contact');
Route::post('/contactm', 'HomeController@contactm')->name('contactm');
Route::post('/reg', 'HomeController@xettuyen')->name('reg');
Route::post('/comment/store', 'CommentController@store')->name('comment.add');
Route::post('/reply/store', 'CommentController@replyStore')->name('reply.add');
Route::get('/{slug}', 'HomeController@allslug')->name('allslug');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;
use Spatie\Permission\Models\Role;
class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
    public function role()
    {
        return $this->belongsTo(Role::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Users\UserRepositoryInterface;
use App\Repositories\Roles\RoleRepositoryInterface;
use Hash;
use DataTables;
class UserController extends Controller
{

    protected $userRepository;
    protected $roleRepository;

    public function __construct(UserRepositoryInterface $userRepository,RoleRepositoryInterface $roleRepository)
    {
        $this->userRepository = $userRepository;
        $this->roleRepository = $roleRepository;
        $this->middleware('permission:user-list', ['only' => ['index']]);
        $this->middleware('permission:user-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:user-edit', ['only' => ['edit', 'update']]);
        //$this->middleware('permission:user-delete', ['only' => ['destroy']]);
        $this->middleware('permission:user-view', ['only' => ['show']]);

    }
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            $data = $this->userRepository->get();
            return Datatables::of($data)
                ->addIndexColumn()
                ->addColumn('role', function($row){
                    $rolename = "";
                    if(!empty($row->roles)){
                        foreach($row->roles as $role){
                            $rolename = $role['name']." ".$rolename;
                        }
                    }else
                    {
                        $rolename = "None";
                    }
                    return $rolename;
                })
                ->rawColumns(['role'])
                ->addColumn('action', function($row){

                    $btn = '<a  href="'.route('user.edit', $row->id).'" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Edit" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill" title="Sửa">
                    <i class="la la-edit"></i>
                    </a> <a  href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="m-portlet__nav-link btn m-btn m-btn--hover-brand m-btn--icon m-btn--icon-only m-btn--pill deleteUser" title="Xóa">
                    <i class="la la-close"></i>
                    </a>';

                    return $btn;
                })
                ->rawColumns(['action'])

                ->make(true);
        }

        return view('admin.user.index');
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $roles = $this->roleRepository->pluck('name','name');
        return view('admin.user.create',compact('roles'));
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ]);
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
        $user = $this->userRepository->create($input);
        $user->assignRole($request->input('roles'));
        return redirect()->route('user.index')
                        ->with('success','User created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = $this->userRepository->find($id);
        return view('admin.user.show',compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = $this->userRepository->find($id);
        $roles = $this->roleRepository->get(); //get all roles
        $userRole = $this->userRepository->getRole($id);
        return view('admin.user.edit',compact('user','roles','userRole'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            'roles' => 'required'
        ]);
        $input = $request->all();
        $user = $this->userRepository->find($id);
        if(!empty($input['password'])){
            $input['password'] = Hash::make($input['password']);
        }else{
            $input['password'] = $user->password;
        }
        $user->update($input);
        $user->assignRole($request->input('roles'));
        return redirect()->route('user.index')
                        ->with('success','User updated successfully');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ($id == 1) {
            return redirect()->back();
        }else {
        $this->userRepository->delete($id);
        return redirect()->route('user.index')
                        ->with('success','User deleted successfully');
        }
    }
}

resources/views/admin/user/create.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1>Tạo mới người dùng</h1>
                </div>

                <div class="panel-body">
                    <!-- Display Validation Errors -->
                    @if(count($errors) > 0)
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    <form class="form-horizontal" role="form" method="POST"
                        action="{{ route('user.store') }}">
                        {{ csrf_field() }}

                        <div
                            class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name"
                                    value="{{ old('name') }}" required autofocus>

                                @if($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div
                            class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">Email:</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control" name="email"
                                    value="{{ old('email') }}" required autofocus>

                                @if($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div class="col-md-6">
                            <label for="image" class="control-label">Ảnh đại diện</label><br>
                            <span class="form-group-btn">
                                <a id="lfm" data-input="image" data-preview="holderuser"
                                    class="btn btn-primary text-white">
                                    <i class="fa fa-picture-o"></i> Chọn
                                </a>
                            </span>
                            <input id="image" class="form-control col-md-6" type="text" name="image"
                                value="{{ old('image') }}">
                            <div id="holderuser" style="margin-top:15px;max-height:100px;">
                                <img src="" alt="" width="100px">
                            </div>
                        </div>
                        <div
                            class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required
                                    autofocus>
                                @if($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div
                            class="form-group{{ $errors->has('confirm-password') ? ' has-error' : '' }}">
                            <label for="confirm-password" class="col-md-4 control-label">Confirm Password</label>

                            <div class="col-md-6">
                                <input id="confirm-password" type="password" class="form-control"
                                    name="confirm-password" required autofocus>
                                @if($errors->has('password_confirmation'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password_confirmation') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div
                            class="form-group{{ $errors->has('roles') ? ' has-error' : '' }}">
                            <label for="roles" class="col-md-4 control-label">Roles</label>

                            <div class="col-md-6">
                                <select id="role" name="roles[]" multiple>
                                    @foreach($roles as $key => $role)
                                        <option value="{{ $key }}">{{ $role }}</option>
                                    @endforeach
                                </select>


                                @if($errors->has('roles'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('roles') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>



                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Save
                                </button>

                                <a class="btn btn-link" href="{{ route('user.index') }}">
                                    Cancel
                                </a>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
<script src="{{ asset('/vendor/laravel-filemanager/js/stand-alone-button.js') }}"></script>

<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script type="text/javascript">
    $('#lfm').filemanager('image');
</script>
@endsection

resources/views/admin/user/edit.blade.php
<?php ?>

@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Edit User</div>

                <div class="panel-body">
                    <!-- Display Validation Errors -->
                    @if(count($errors) > 0)
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> There were some problems with your input.<br><br>
                            <ul>
                                @foreach($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif


                    <form class="form-horizontal" role="form" method="POST"
                        action="{{ route('user.update',$user->id) }}">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}

                        <div
                            class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Name</label>

                            <div class="col-md-6">
                                <input id="display_name" type="text" class="form-control" name="name"
                                    value="{{ $user->name }}" required autofocus>

                                @if($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                        <div
                            class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail</label>

                            <div class="col-md-6">
                                <input id="email" type="text" class="form-control" name="email"
                                    value="{{ $user->email }}" required autofocus>

                                @if($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>


                </div>
                <div class="col-md-12">
                    <label for="image" class="control-label">Ảnh đại diện</label><br>
                    <span class="form-group-btn">
                        <a id="lfm" data-input="image" data-preview="holderuser" class="btn btn-primary text-white">
                            <i class="fa fa-picture-o"></i> Chọn
                        </a>
                    </span>
                    <input id="image" class="form-control col-md-12" type="text" name="image"
                        value="{{ $user->image }}">
                    <div id="holderuser" style="margin-top:15px;max-height:100px;">
                        <img src="{{ asset($user->image) }}" alt="" width="100px">
                    </div>
                </div>

                <div
                    class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                    <label for="password" class="col-md-4 control-label">Password</label>

                    <div class="col-md-6">
                        <input id="password" type="password" class="form-control" name="password" autofocus>
                        @if($errors->has('password'))
                            <span class="help-block">
                                <strong>{{ $errors->first('password') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div
                    class="form-group{{ $errors->has('confirm-password') ? ' has-error' : '' }}">
                    <label for="confirm-password" class="col-md-4 control-label">Confirm Password</label>

                    <div class="col-md-6">
                        <input id="confirm-password" type="password" class="form-control" name="confirm-password"
                            autofocus>
                        @if($errors->has('confirm-password'))
                            <span class="help-block">
                                <strong>{{ $errors->first('confirm-password') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>


                <div
                    class="form-group{{ $errors->has('roles') ? ' has-error' : '' }}">
                    <label for="roles" class="col-md-4 control-label">Roles</label>

                    <div class="col-md-6">

                        <select id="role" name="roles[]" multiple>
                            @foreach($roles as $role)
                                <option value="{{ $role->id }}"
                                    {{ in_array($role->id, $userRole) ? "selected" : null }}>
                                    {{ $role->name }}
                                </option>
                            @endforeach
                        </select>

                        @if($errors->has('roles'))
                            <span class="help-block">
                                <strong>{{ $errors->first('roles') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>


                <div class="form-group">
                    <div class="col-md-8 col-md-offset-4">
                        <button type="submit" class="btn btn-primary">
                            Update
                        </button>

                        <a class="btn btn-link" href="{{ route('user.index') }}">
                            Cancel
                        </a>
                    </div>
                </div>
                </form>

            </div>
        </div>
    </div>
</div>
</div>
{{-- <script src="{{ asset('js/tinymce.min.js') }}"></script> --}}

<script src="{{ asset('/vendor/laravel-filemanager/js/stand-alone-button.js') }}"></script>

<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script type="text/javascript">
    $('#lfm').filemanager('image');
</script>
@endsection

resources/views/admin/user/index.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')


<div class="container-fluid">
    <div class="col-md-12">
        @if($message = Session::get('success'))
            <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert"></button>
                <strong>{{ $message }}</strong>
            </div>
        @endif
    </div>
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        Người Dùng
                    </h3>
                </div>
            </div>
            <div class="m-portlet__head-tools">
                <ul class="m-portlet__nav">
                    <li class="m-portlet__nav-item">
                    </li>
                </ul>
            </div>
        </div>
        <div class="m-portlet__body">
            <!--begin: Search Form -->
            <div class="m-form m-form--label-align-right m--margin-top-20 m--margin-bottom-30">
                <div class="row align-items-center">
                    <div class="col-xl-8 order-2 order-xl-1">

                    </div>
                    <div class="col-xl-4 order-1 order-xl-2 m--align-right">
                        <a href="{{ route('user.create') }}"
                            class="btn btn-info m-btn m-btn--custom m-btn--pill m-btn--icon m-btn--air">
                            <span>
                                <i class="la la-cart-plus"></i>
                                <span>New User</span>
                            </span>
                        </a>
                        <div class="m-separator m-separator--dashed d-xl-none"></div>
                    </div>
                </div>
            </div>
            <!--end: Search Form -->

            <!--begin: Datatable -->
            <div class="m_datatable" id="child_data_ajax">

                <table class="data-table m-datatable__table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Role</th>
                            <th width="100px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    </tbody>
                </table>
            </div>
            <!--end: Datatable -->
        </div>
    </div>

</div>

@routes

    <script type="text/javascript">
        $(document).ready(function () {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            var table = $('.data-table').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('user.index') }}",
                columns: [{
                        data: 'DT_RowIndex',
                        name: 'DT_RowIndex'
                    },
                    {
                        data: 'name',
                        name: 'name'
                    },
                    {
                        data: 'email',
                        name: 'email'
                    },
                    {
                        data: 'role',
                        name: 'role'
                    },
                    {
                        data: 'action',
                        name: 'action',
                        orderable: false,
                        searchable: false
                    },
                ]
            });

            $('body').on('click', '.deleteUser', function () {
                //$(".deleteUser").click(function(){

                var page_id = $(this).data("id");
                var r = confirm("Bạn chắc chắn muốn xóa !");
                if (r == true) {
                    $.ajax({
                        type: "POST",
                        data: {
                            _method: 'delete'
                        },
                        url: route('user.destroy', {
                            id: page_id
                        }),
                        success: function (data) {
                            table.draw();
                        },
                        error: function (data) {
                            console.log('Error:', data);
                        }
                    });
                } else {
                    return false;
                }

            });
            $(".alert").fadeTo(2000, 500).slideUp(500, function () {
                $(".alert").slideUp(500);
            });

        });
    </script>
    </div>
    @endsection

    @push('scripts')
    @endpush

resources/views/admin/user/show.blade.php
<?php ?>
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">User Info</div>

                    <div class="panel-body">


                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Name</label>
                            {{ $user->name }}
                        </div>


                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">E-mail</label>
                            {{ $user->email }}
                        </div>


                        <div class="form-group">
                            <label for="name" class="col-md-4 control-label">Roles</label>
                            @if(!empty($user->roles))
                                @foreach($user->roles as $role)
                                    <label class="label label-success">{{ $role->display_name }}</label>
                                @endforeach
                            @endif
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection